on: 
  push:
    paths-ignore:
      - "README.md"
      - "**.json"
      - "action.yml"
  schedule:
    - cron: 15 14 * * 6
  workflow_dispatch:

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Test repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #quick: true
          #url: "https://www.github.com/dancancro/great-big-example-application"
          #url: "https://github.com/Lerer/verademo"
          #create-issues: false 
          #allow-dirty: false
          #recursive: true
          fail-on-cvss: 1
          debug: true
        continue-on-error: true
      # - name: free text
      #   run: |
      #     curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan --url https://www.github.com/dancancro/great-big-example-application --debug 
      #   env:
      #     SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}

        